os: linux
language: cpp
dist: focal
compiler: g++

git:
  depth: 1
  quiet: true

deploy:
  provider: releases
  token: $GH_OAUTH
  file: "JuceDoc"
  cleanup: false
  edge: true
  on:
    tags: true

jobs:
  include:
    - os: linux
      addons:
        apt:
          update: true
          packages:
            - g++-9
            - cmake-data
            - cmake
            - libgraphviz-dev
            - libx11-dev
            - libxinerama-dev
            - libxrandr-dev
            - libxcursor-dev
            - libfreetype6-dev
            - libxcomposite-dev
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  - make -j3
