image: Ubuntu

configuration:
- Debug

clone_script:
- cmd: |-
    git clone --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    git checkout -f %APPVEYOR_REPO_COMMIT%

install:
- sudo apt update -qq && sudo apt install -qq
- sudo apt -y install build-essential git cmake
- sudo apt -y install libgraphviz-dev
- ls

cache:
- '/usr/lib/x86_64-linux-gnu/'

before_build:
- cmd: |-
    cd %APPVEYOR_BUILD_FOLDER%
    mkdir build
    cd build
    cmake --version
    cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..

build_script:
- make
